import type { AccountTemplate } from "./types";

/** Belgian Plan Comptable Minimum Normalise (PCMN) chart of accounts */
export const BE_ACCOUNTS: AccountTemplate[] = [
  // Class 1: Equity, Provisions, Long-term Debt
  { code: "100", name: "Share Capital", type: "equity", subType: "equity" },
  { code: "110", name: "Share Premium", type: "equity", subType: "equity" },
  { code: "130", name: "Legal Reserve", type: "equity", subType: "equity" },
  { code: "133", name: "Available Reserves", type: "equity", subType: "equity" },
  { code: "140", name: "Accumulated Profits", type: "equity", subType: "retained" },
  { code: "141", name: "Accumulated Losses", type: "equity", subType: "retained" },
  { code: "160", name: "Provisions for Pensions", type: "liability", subType: "non_current" },
  { code: "163", name: "Provisions for Liabilities and Charges", type: "liability", subType: "non_current" },
  { code: "173", name: "Bank Loans (Long-term)", type: "liability", subType: "non_current" },
  { code: "174", name: "Other Long-term Loans", type: "liability", subType: "non_current" },
  // Class 2: Fixed Assets
  { code: "211", name: "Concessions, Patents and Licences", type: "asset", subType: "fixed" },
  { code: "220", name: "Land", type: "asset", subType: "fixed" },
  { code: "221", name: "Buildings", type: "asset", subType: "fixed" },
  { code: "230", name: "Plant, Machinery and Equipment", type: "asset", subType: "fixed" },
  { code: "240", name: "Furniture and Fixtures", type: "asset", subType: "fixed" },
  { code: "241", name: "Vehicles", type: "asset", subType: "fixed" },
  { code: "280", name: "Participating Interests", type: "asset", subType: "fixed" },
  // Class 3: Inventories
  { code: "300", name: "Raw Materials", type: "asset", subType: "current" },
  { code: "330", name: "Finished Goods", type: "asset", subType: "current" },
  { code: "340", name: "Goods Purchased for Resale", type: "asset", subType: "current" },
  // Class 4: Third-party Accounts
  { code: "400", name: "Trade Receivables", type: "asset", subType: "current" },
  { code: "407", name: "Doubtful Receivables", type: "asset", subType: "current" },
  { code: "411", name: "VAT Recoverable", type: "asset", subType: "current" },
  { code: "416", name: "Sundry Receivables", type: "asset", subType: "current" },
  { code: "440", name: "Trade Payables", type: "liability", subType: "current" },
  { code: "451", name: "VAT Payable", type: "liability", subType: "current" },
  { code: "452", name: "Taxes Payable", type: "liability", subType: "current" },
  { code: "453", name: "Withholding Taxes Payable", type: "liability", subType: "current" },
  { code: "454", name: "Social Security Contributions Payable", type: "liability", subType: "current" },
  { code: "455", name: "Remuneration Payable", type: "liability", subType: "current" },
  { code: "489", name: "Other Amounts Payable", type: "liability", subType: "current" },
  { code: "490", name: "Deferred Charges", type: "asset", subType: "current" },
  { code: "493", name: "Deferred Income", type: "liability", subType: "current" },
  // Class 5: Financial Accounts
  { code: "550", name: "Bank Accounts", type: "asset", subType: "current" },
  { code: "570", name: "Petty Cash", type: "asset", subType: "current" },
  // Class 6: Expenses
  { code: "600", name: "Purchases of Raw Materials", type: "expense", subType: "cogs" },
  { code: "604", name: "Purchases of Goods for Resale", type: "expense", subType: "cogs" },
  { code: "610", name: "Rent and Rental Charges", type: "expense", subType: "operating" },
  { code: "611", name: "Supplies and Utilities", type: "expense", subType: "operating" },
  { code: "613", name: "Insurance", type: "expense", subType: "operating" },
  { code: "614", name: "Transport and Freight", type: "expense", subType: "operating" },
  { code: "615", name: "Professional Fees", type: "expense", subType: "operating" },
  { code: "616", name: "Post, Telecom and Travel", type: "expense", subType: "operating" },
  { code: "619", name: "Marketing and Advertising", type: "expense", subType: "operating" },
  { code: "620", name: "Salaries and Wages", type: "expense", subType: "operating" },
  { code: "621", name: "Employer Social Security Contributions", type: "expense", subType: "operating" },
  { code: "630", name: "Depreciation and Amortisation", type: "expense", subType: "operating" },
  { code: "640", name: "Operating Taxes", type: "expense", subType: "operating" },
  { code: "650", name: "Interest and Debt Charges", type: "expense", subType: "non_operating" },
  { code: "659", name: "Bank Charges", type: "expense", subType: "non_operating" },
  { code: "670", name: "Income Taxes", type: "expense", subType: "tax" },
  // Class 7: Revenue
  { code: "700", name: "Sales of Goods and Services", type: "revenue", subType: "operating" },
  { code: "701", name: "Sales of Goods", type: "revenue", subType: "operating" },
  { code: "702", name: "Services Rendered", type: "revenue", subType: "operating" },
  { code: "740", name: "Operating Subsidies Received", type: "revenue", subType: "non_operating" },
  { code: "741", name: "Gain on Disposal of Fixed Assets", type: "revenue", subType: "non_operating" },
  { code: "745", name: "Rental Income", type: "revenue", subType: "non_operating" },
  { code: "749", name: "Miscellaneous Operating Income", type: "revenue", subType: "non_operating" },
  { code: "751", name: "Income from Current Assets", type: "revenue", subType: "non_operating" },
  { code: "757", name: "Discounts Obtained", type: "revenue", subType: "non_operating" },
];
