import type { AccountTemplate } from "./types";

/** Brazilian chart of accounts (CFC/ITG 1000 / SPED compatible) */
export const BR_ACCOUNTS: AccountTemplate[] = [
  // 1 - Assets (Ativo)
  { code: "1.1.01", name: "Cash", type: "asset", subType: "current" },
  { code: "1.1.02", name: "Banks - Checking Account", type: "asset", subType: "current" },
  { code: "1.1.03", name: "Short-term Investments", type: "asset", subType: "current" },
  { code: "1.1.04", name: "Accounts Receivable", type: "asset", subType: "current" },
  { code: "1.1.05", name: "(-) Allowance for Doubtful Accounts", type: "asset", subType: "current" },
  { code: "1.1.06", name: "Advances to Suppliers", type: "asset", subType: "current" },
  { code: "1.1.08", name: "Taxes Recoverable", type: "asset", subType: "current" },
  { code: "1.1.10", name: "Merchandise Inventory", type: "asset", subType: "current" },
  { code: "1.1.12", name: "Raw Materials Inventory", type: "asset", subType: "current" },
  { code: "1.1.15", name: "Prepaid Expenses", type: "asset", subType: "current" },
  { code: "1.3.05", name: "Land", type: "asset", subType: "fixed" },
  { code: "1.3.06", name: "Buildings", type: "asset", subType: "fixed" },
  { code: "1.3.07", name: "Machinery and Equipment", type: "asset", subType: "fixed" },
  { code: "1.3.08", name: "Vehicles", type: "asset", subType: "fixed" },
  { code: "1.3.09", name: "Furniture and Fixtures", type: "asset", subType: "fixed" },
  { code: "1.3.10", name: "(-) Accumulated Depreciation", type: "asset", subType: "fixed" },
  { code: "1.3.11", name: "Software", type: "asset", subType: "fixed" },
  // 2 - Liabilities (Passivo)
  { code: "2.1.01", name: "Trade Payables (Suppliers)", type: "liability", subType: "current" },
  { code: "2.1.02", name: "Bank Loans - Short-term", type: "liability", subType: "current" },
  { code: "2.1.04", name: "Simples Nacional Payable", type: "liability", subType: "current" },
  { code: "2.1.05", name: "ICMS Payable", type: "liability", subType: "current" },
  { code: "2.1.06", name: "ISS Payable", type: "liability", subType: "current" },
  { code: "2.1.07", name: "PIS/COFINS Payable", type: "liability", subType: "current" },
  { code: "2.1.08", name: "Income Tax Payable (IRPJ)", type: "liability", subType: "current" },
  { code: "2.1.09", name: "Social Contribution Payable (CSLL)", type: "liability", subType: "current" },
  { code: "2.1.10", name: "Wages and Salaries Payable", type: "liability", subType: "current" },
  { code: "2.1.11", name: "FGTS Payable", type: "liability", subType: "current" },
  { code: "2.1.12", name: "INSS Payable", type: "liability", subType: "current" },
  { code: "2.1.13", name: "Vacation Accrual", type: "liability", subType: "current" },
  { code: "2.1.14", name: "13th Salary Accrual", type: "liability", subType: "current" },
  { code: "2.1.18", name: "Other Accounts Payable", type: "liability", subType: "current" },
  { code: "2.2.01", name: "Bank Loans - Long-term", type: "liability", subType: "non_current" },
  { code: "2.2.03", name: "Loans from Partners/Shareholders", type: "liability", subType: "non_current" },
  // 3 - Equity (Patrimonio Liquido)
  { code: "3.1.01", name: "Subscribed Capital", type: "equity", subType: "equity" },
  { code: "3.2.01", name: "Capital Reserves", type: "equity", subType: "equity" },
  { code: "3.2.02", name: "Profit Reserves", type: "equity", subType: "equity" },
  { code: "3.3.01", name: "Retained Earnings", type: "equity", subType: "retained" },
  { code: "3.3.02", name: "(-) Accumulated Losses", type: "equity", subType: "retained" },
  // 4 - Revenue (Receitas)
  { code: "4.1.01", name: "Product Sales Revenue", type: "revenue", subType: "operating" },
  { code: "4.1.02", name: "Merchandise Sales Revenue", type: "revenue", subType: "operating" },
  { code: "4.1.03", name: "Service Revenue", type: "revenue", subType: "operating" },
  { code: "4.1.04", name: "(-) Sales Taxes and Deductions", type: "revenue", subType: "operating" },
  { code: "4.2.01", name: "Interest Income", type: "revenue", subType: "non_operating" },
  { code: "4.3.01", name: "Gain on Sale of Fixed Assets", type: "revenue", subType: "non_operating" },
  { code: "4.3.02", name: "Other Operating Revenue", type: "revenue", subType: "non_operating" },
  // 5 - Expenses / Costs (Custos e Despesas)
  { code: "5.1.01", name: "Cost of Materials/Inputs", type: "expense", subType: "cogs" },
  { code: "5.1.04", name: "Cost of Merchandise Sold", type: "expense", subType: "cogs" },
  { code: "5.1.05", name: "Cost of Services Rendered", type: "expense", subType: "cogs" },
  { code: "5.2.03", name: "Payroll Expenses", type: "expense", subType: "operating" },
  { code: "5.2.04", name: "Social Charges (INSS/FGTS)", type: "expense", subType: "operating" },
  { code: "5.2.05", name: "Rent Expense", type: "expense", subType: "operating" },
  { code: "5.2.06", name: "Utilities Expense", type: "expense", subType: "operating" },
  { code: "5.2.07", name: "Depreciation and Amortization", type: "expense", subType: "operating" },
  { code: "5.2.08", name: "Professional Services", type: "expense", subType: "operating" },
  { code: "5.2.09", name: "Insurance Expense", type: "expense", subType: "operating" },
  { code: "5.2.10", name: "Other General Expenses", type: "expense", subType: "operating" },
  { code: "5.3.01", name: "Interest Expense", type: "expense", subType: "non_operating" },
  { code: "5.3.02", name: "Bank Fees and Charges", type: "expense", subType: "non_operating" },
];
