import type { AccountTemplate } from "./types";

/** German SKR03 (Standardkontenrahmen 03) chart of accounts */
export const DE_ACCOUNTS: AccountTemplate[] = [
  // Class 0: Fixed Assets & Capital
  { code: "0027", name: "Software", type: "asset", subType: "fixed" },
  { code: "0050", name: "Land & Buildings", type: "asset", subType: "fixed" },
  { code: "0100", name: "Developed Land", type: "asset", subType: "fixed" },
  { code: "0200", name: "Technical Equipment & Machinery", type: "asset", subType: "fixed" },
  { code: "0300", name: "Other Equipment, Furniture & Fixtures", type: "asset", subType: "fixed" },
  { code: "0320", name: "Passenger Vehicles", type: "asset", subType: "fixed" },
  { code: "0420", name: "Office Furniture & Equipment", type: "asset", subType: "fixed" },
  { code: "0480", name: "Low-Value Assets", type: "asset", subType: "fixed" },
  { code: "0630", name: "Liabilities to Credit Institutions", type: "liability", subType: "non_current" },
  { code: "0750", name: "Liabilities to Shareholders", type: "liability", subType: "non_current" },
  { code: "0800", name: "Subscribed Capital", type: "equity", subType: "equity" },
  { code: "0840", name: "Capital Reserve", type: "equity", subType: "equity" },
  { code: "0850", name: "Revenue Reserves (Legal Reserve)", type: "equity", subType: "equity" },
  { code: "0860", name: "Profit Carried Forward", type: "equity", subType: "retained" },
  { code: "0868", name: "Loss Carried Forward", type: "equity", subType: "retained" },
  { code: "0880", name: "Variable Capital (Sole Proprietor)", type: "equity", subType: "equity" },
  { code: "0955", name: "Tax Provisions", type: "liability", subType: "current" },
  { code: "0970", name: "Other Provisions", type: "liability", subType: "current" },
  // Class 1: Financial Accounts
  { code: "1000", name: "Cash on Hand", type: "asset", subType: "current" },
  { code: "1200", name: "Bank", type: "asset", subType: "current" },
  { code: "1400", name: "Trade Receivables", type: "asset", subType: "current" },
  { code: "1500", name: "Other Assets", type: "asset", subType: "current" },
  { code: "1518", name: "Advance Payments Made", type: "asset", subType: "current" },
  { code: "1576", name: "Input Tax 19%", type: "asset", subType: "current" },
  { code: "1600", name: "Trade Payables", type: "liability", subType: "current" },
  { code: "1700", name: "Other Payables", type: "liability", subType: "current" },
  { code: "1742", name: "Social Security Payables", type: "liability", subType: "current" },
  { code: "1776", name: "VAT Payable 19%", type: "liability", subType: "current" },
  // Class 2: Financial Income & Expense
  { code: "2100", name: "Interest Expense", type: "expense", subType: "non_operating" },
  { code: "2200", name: "Corporate Income Tax Expense", type: "expense", subType: "tax" },
  { code: "2650", name: "Interest Income", type: "revenue", subType: "non_operating" },
  // Class 3: Materials Purchased
  { code: "3000", name: "Raw Materials Purchased", type: "expense", subType: "cogs" },
  { code: "3100", name: "Outsourced Services", type: "expense", subType: "cogs" },
  { code: "3400", name: "Goods Purchased (19% VAT)", type: "expense", subType: "cogs" },
  // Class 4: Operating Expenses
  { code: "4100", name: "Wages & Salaries", type: "expense", subType: "operating" },
  { code: "4120", name: "Salaries", type: "expense", subType: "operating" },
  { code: "4130", name: "Statutory Social Security Contributions", type: "expense", subType: "operating" },
  { code: "4210", name: "Rent", type: "expense", subType: "operating" },
  { code: "4240", name: "Gas, Electricity, Water", type: "expense", subType: "operating" },
  { code: "4260", name: "Maintenance of Business Premises", type: "expense", subType: "operating" },
  { code: "4500", name: "Vehicle Costs", type: "expense", subType: "operating" },
  { code: "4530", name: "Running Vehicle Costs (Fuel)", type: "expense", subType: "operating" },
  { code: "4600", name: "Advertising Costs", type: "expense", subType: "operating" },
  { code: "4660", name: "Travel Expenses (Employee)", type: "expense", subType: "operating" },
  { code: "4730", name: "Postage & Freight", type: "expense", subType: "operating" },
  { code: "4800", name: "Repairs & Maintenance", type: "expense", subType: "operating" },
  { code: "4830", name: "Depreciation on Tangible Fixed Assets", type: "expense", subType: "operating" },
  { code: "4920", name: "Telephone", type: "expense", subType: "operating" },
  { code: "4925", name: "Internet", type: "expense", subType: "operating" },
  { code: "4930", name: "Office Supplies", type: "expense", subType: "operating" },
  { code: "4950", name: "Legal & Consulting Fees", type: "expense", subType: "operating" },
  { code: "4955", name: "Bookkeeping & Audit Fees", type: "expense", subType: "operating" },
  { code: "4970", name: "Bank Charges", type: "expense", subType: "operating" },
  { code: "4980", name: "Insurance (Business)", type: "expense", subType: "operating" },
  // Class 8: Revenue
  { code: "8000", name: "Revenue (General)", type: "revenue", subType: "operating" },
  { code: "8100", name: "Tax-Exempt Revenue (Domestic)", type: "revenue", subType: "operating" },
  { code: "8120", name: "Tax-Exempt Revenue (Export)", type: "revenue", subType: "operating" },
  { code: "8400", name: "Revenue (19% VAT)", type: "revenue", subType: "operating" },
  { code: "8600", name: "Other Operating Income", type: "revenue", subType: "non_operating" },
  { code: "8820", name: "Gains on Disposal of Fixed Assets", type: "revenue", subType: "non_operating" },
];
