import type { AccountTemplate } from "./types";

/** Spanish Plan General de Contabilidad (PGC) chart of accounts */
export const ES_ACCOUNTS: AccountTemplate[] = [
  // Group 1: Financing (Equity & Long-term Liabilities)
  { code: "100", name: "Share Capital", type: "equity", subType: "equity" },
  { code: "112", name: "Legal Reserve", type: "equity", subType: "equity" },
  { code: "113", name: "Voluntary Reserves", type: "equity", subType: "equity" },
  { code: "118", name: "Owner Contributions", type: "equity", subType: "equity" },
  { code: "120", name: "Retained Earnings", type: "equity", subType: "retained" },
  { code: "129", name: "Profit / Loss for the Year", type: "equity", subType: "equity" },
  { code: "170", name: "Long-term Bank Loans", type: "liability", subType: "non_current" },
  { code: "171", name: "Long-term Debts", type: "liability", subType: "non_current" },
  { code: "174", name: "Long-term Finance Lease Payable", type: "liability", subType: "non_current" },
  // Group 2: Fixed Assets
  { code: "206", name: "Computer Software", type: "asset", subType: "fixed" },
  { code: "210", name: "Land and Natural Resources", type: "asset", subType: "fixed" },
  { code: "211", name: "Buildings", type: "asset", subType: "fixed" },
  { code: "213", name: "Machinery", type: "asset", subType: "fixed" },
  { code: "216", name: "Furniture", type: "asset", subType: "fixed" },
  { code: "217", name: "Computer Equipment", type: "asset", subType: "fixed" },
  { code: "218", name: "Vehicles", type: "asset", subType: "fixed" },
  { code: "280", name: "Accum. Amortisation - Intangible Assets", type: "asset", subType: "fixed" },
  { code: "281", name: "Accum. Depreciation - Tangible Assets", type: "asset", subType: "fixed" },
  // Group 3: Inventories
  { code: "300", name: "Goods for Resale", type: "asset", subType: "current" },
  { code: "310", name: "Raw Materials", type: "asset", subType: "current" },
  { code: "350", name: "Finished Goods", type: "asset", subType: "current" },
  // Group 4: Creditors and Debtors
  { code: "400", name: "Trade Suppliers", type: "liability", subType: "current" },
  { code: "410", name: "Creditors for Services", type: "liability", subType: "current" },
  { code: "430", name: "Trade Receivables", type: "asset", subType: "current" },
  { code: "436", name: "Doubtful Receivables", type: "asset", subType: "current" },
  { code: "460", name: "Salary Advances to Employees", type: "asset", subType: "current" },
  { code: "465", name: "Wages Payable", type: "liability", subType: "current" },
  { code: "470", name: "Tax Receivables", type: "asset", subType: "current" },
  { code: "472", name: "Input VAT", type: "asset", subType: "current" },
  { code: "475", name: "Tax Payables", type: "liability", subType: "current" },
  { code: "476", name: "Social Security Payable", type: "liability", subType: "current" },
  { code: "477", name: "Output VAT", type: "liability", subType: "current" },
  { code: "480", name: "Prepaid Expenses", type: "asset", subType: "current" },
  { code: "490", name: "Allowance for Doubtful Receivables", type: "asset", subType: "current" },
  // Group 5: Financial Accounts
  { code: "520", name: "Short-term Bank Loans", type: "liability", subType: "current" },
  { code: "570", name: "Petty Cash", type: "asset", subType: "current" },
  { code: "572", name: "Bank Accounts", type: "asset", subType: "current" },
  // Group 6: Purchases and Expenses
  { code: "600", name: "Purchases of Goods for Resale", type: "expense", subType: "cogs" },
  { code: "601", name: "Purchases of Raw Materials", type: "expense", subType: "cogs" },
  { code: "607", name: "Subcontracted Work", type: "expense", subType: "cogs" },
  { code: "621", name: "Rent and Leases", type: "expense", subType: "operating" },
  { code: "622", name: "Repairs and Maintenance", type: "expense", subType: "operating" },
  { code: "623", name: "Professional Services", type: "expense", subType: "operating" },
  { code: "624", name: "Transport", type: "expense", subType: "operating" },
  { code: "625", name: "Insurance Premiums", type: "expense", subType: "operating" },
  { code: "626", name: "Banking and Similar Services", type: "expense", subType: "operating" },
  { code: "627", name: "Advertising and Public Relations", type: "expense", subType: "operating" },
  { code: "628", name: "Utilities", type: "expense", subType: "operating" },
  { code: "629", name: "Other Services", type: "expense", subType: "operating" },
  { code: "630", name: "Income Tax", type: "expense", subType: "tax" },
  { code: "640", name: "Wages and Salaries", type: "expense", subType: "operating" },
  { code: "642", name: "Employer Social Security", type: "expense", subType: "operating" },
  { code: "662", name: "Interest on Debts", type: "expense", subType: "non_operating" },
  { code: "668", name: "Foreign Exchange Losses", type: "expense", subType: "non_operating" },
  { code: "680", name: "Amortisation of Intangible Assets", type: "expense", subType: "operating" },
  { code: "681", name: "Depreciation of Tangible Assets", type: "expense", subType: "operating" },
  // Group 7: Sales and Income
  { code: "700", name: "Sales of Goods", type: "revenue", subType: "operating" },
  { code: "705", name: "Revenue from Services", type: "revenue", subType: "operating" },
  { code: "740", name: "Operating Grants", type: "revenue", subType: "non_operating" },
  { code: "752", name: "Rental Income", type: "revenue", subType: "non_operating" },
  { code: "759", name: "Miscellaneous Income", type: "revenue", subType: "non_operating" },
  { code: "762", name: "Interest Income", type: "revenue", subType: "non_operating" },
  { code: "768", name: "Foreign Exchange Gains", type: "revenue", subType: "non_operating" },
  { code: "771", name: "Gains on Disposal of Tangible Assets", type: "revenue", subType: "non_operating" },
];
