import type { AccountTemplate } from "./types";

/** French Plan Comptable General (PCG) chart of accounts */
export const FR_ACCOUNTS: AccountTemplate[] = [
  // Class 1: Capital Accounts (Equity, Reserves, Loans)
  { code: "101", name: "Share Capital", type: "equity", subType: "equity" },
  { code: "106", name: "Reserves", type: "equity", subType: "equity" },
  { code: "1061", name: "Legal Reserve", type: "equity", subType: "equity" },
  { code: "108", name: "Owner's Account (Sole Proprietor)", type: "equity", subType: "equity" },
  { code: "110", name: "Retained Earnings", type: "equity", subType: "retained" },
  { code: "119", name: "Accumulated Losses", type: "equity", subType: "retained" },
  { code: "120", name: "Profit for the Year", type: "equity", subType: "equity" },
  { code: "129", name: "Loss for the Year", type: "equity", subType: "equity" },
  { code: "131", name: "Investment Grants Received", type: "equity", subType: "equity" },
  { code: "151", name: "Provisions for Litigation", type: "liability", subType: "non_current" },
  { code: "155", name: "Provisions for Taxes", type: "liability", subType: "non_current" },
  { code: "164", name: "Bank Loans", type: "liability", subType: "non_current" },
  { code: "168", name: "Other Borrowings", type: "liability", subType: "non_current" },
  // Class 2: Fixed Assets (Immobilisations)
  { code: "205", name: "Concessions and Similar Rights", type: "asset", subType: "fixed" },
  { code: "2051", name: "Software", type: "asset", subType: "fixed" },
  { code: "207", name: "Goodwill", type: "asset", subType: "fixed" },
  { code: "211", name: "Land", type: "asset", subType: "fixed" },
  { code: "213", name: "Buildings", type: "asset", subType: "fixed" },
  { code: "215", name: "Technical Installations, Equipment & Tools", type: "asset", subType: "fixed" },
  { code: "218", name: "Other Tangible Fixed Assets", type: "asset", subType: "fixed" },
  { code: "2182", name: "Vehicles", type: "asset", subType: "fixed" },
  { code: "2183", name: "Office Equipment & Computer Hardware", type: "asset", subType: "fixed" },
  { code: "2184", name: "Furniture", type: "asset", subType: "fixed" },
  { code: "261", name: "Equity Investments", type: "asset", subType: "fixed" },
  { code: "280", name: "Accum. Amortisation - Intangible Assets", type: "asset", subType: "fixed" },
  { code: "281", name: "Accum. Depreciation - Tangible Assets", type: "asset", subType: "fixed" },
  // Class 3: Inventories (Stocks)
  { code: "31", name: "Raw Materials", type: "asset", subType: "current" },
  { code: "35", name: "Finished Goods", type: "asset", subType: "current" },
  { code: "37", name: "Goods for Resale", type: "asset", subType: "current" },
  // Class 4: Third-party Accounts
  { code: "401", name: "Trade Suppliers", type: "liability", subType: "current" },
  { code: "404", name: "Suppliers - Fixed Assets", type: "liability", subType: "current" },
  { code: "408", name: "Suppliers - Invoices Not Yet Received", type: "liability", subType: "current" },
  { code: "411", name: "Trade Receivables", type: "asset", subType: "current" },
  { code: "416", name: "Doubtful Receivables", type: "asset", subType: "current" },
  { code: "421", name: "Wages Payable", type: "liability", subType: "current" },
  { code: "431", name: "Social Security Payable", type: "liability", subType: "current" },
  { code: "4456", name: "Input VAT (TVA deductible)", type: "asset", subType: "current" },
  { code: "4457", name: "Output VAT (TVA collectee)", type: "liability", subType: "current" },
  { code: "444", name: "Income Tax Payable", type: "liability", subType: "current" },
  { code: "445", name: "Tax Payables", type: "liability", subType: "current" },
  { code: "467", name: "Other Receivables / Payables", type: "asset", subType: "current" },
  { code: "486", name: "Prepaid Expenses", type: "asset", subType: "current" },
  { code: "487", name: "Deferred Income", type: "liability", subType: "current" },
  { code: "491", name: "Allowance for Doubtful Receivables", type: "asset", subType: "current" },
  // Class 5: Financial Accounts (Cash, Bank)
  { code: "512", name: "Bank Accounts", type: "asset", subType: "current" },
  { code: "530", name: "Petty Cash", type: "asset", subType: "current" },
  { code: "519", name: "Short-term Bank Credit", type: "liability", subType: "current" },
  // Class 6: Expenses (Charges)
  { code: "601", name: "Purchases of Raw Materials", type: "expense", subType: "cogs" },
  { code: "607", name: "Purchases of Goods for Resale", type: "expense", subType: "cogs" },
  { code: "611", name: "Subcontracting", type: "expense", subType: "operating" },
  { code: "613", name: "Rent", type: "expense", subType: "operating" },
  { code: "6155", name: "Maintenance and Repairs", type: "expense", subType: "operating" },
  { code: "616", name: "Insurance Premiums", type: "expense", subType: "operating" },
  { code: "6226", name: "Accounting Fees", type: "expense", subType: "operating" },
  { code: "6227", name: "Legal Fees", type: "expense", subType: "operating" },
  { code: "623", name: "Advertising and Publications", type: "expense", subType: "operating" },
  { code: "624", name: "Transport of Goods", type: "expense", subType: "operating" },
  { code: "625", name: "Travel, Accommodation and Entertainment", type: "expense", subType: "operating" },
  { code: "626", name: "Postage and Telecom", type: "expense", subType: "operating" },
  { code: "627", name: "Banking Services", type: "expense", subType: "operating" },
  { code: "6241", name: "Transport of Purchases", type: "expense", subType: "operating" },
  { code: "63", name: "Taxes and Similar Charges", type: "expense", subType: "operating" },
  { code: "635", name: "Other Taxes (CFE, CVAE)", type: "expense", subType: "operating" },
  { code: "641", name: "Wages and Salaries", type: "expense", subType: "operating" },
  { code: "645", name: "Employer Social Security Contributions", type: "expense", subType: "operating" },
  { code: "661", name: "Interest on Loans", type: "expense", subType: "non_operating" },
  { code: "666", name: "Foreign Exchange Losses", type: "expense", subType: "non_operating" },
  { code: "681", name: "Depreciation - Operating", type: "expense", subType: "operating" },
  { code: "695", name: "Corporate Income Tax", type: "expense", subType: "tax" },
  // Class 7: Revenue (Produits)
  { code: "701", name: "Sales of Finished Products", type: "revenue", subType: "operating" },
  { code: "706", name: "Revenue from Services", type: "revenue", subType: "operating" },
  { code: "707", name: "Sales of Goods for Resale", type: "revenue", subType: "operating" },
  { code: "708", name: "Ancillary Revenue", type: "revenue", subType: "operating" },
  { code: "740", name: "Operating Grants", type: "revenue", subType: "non_operating" },
  { code: "752", name: "Rental Income", type: "revenue", subType: "non_operating" },
  { code: "758", name: "Other Operating Income", type: "revenue", subType: "non_operating" },
  { code: "761", name: "Investment Income", type: "revenue", subType: "non_operating" },
  { code: "766", name: "Foreign Exchange Gains", type: "revenue", subType: "non_operating" },
  { code: "775", name: "Gains on Disposal of Fixed Assets", type: "revenue", subType: "non_operating" },
];
