import type { AccountTemplate } from "./types";

/** Generic US GAAP-style chart of accounts (used for US, CA, GB, AU, NZ, etc.) */
export const GENERIC_ACCOUNTS: AccountTemplate[] = [
  // Assets (1xxx)
  { code: "1000", name: "Cash", type: "asset", subType: "current" },
  { code: "1010", name: "Petty Cash", type: "asset", subType: "current" },
  { code: "1100", name: "Checking Account", type: "asset", subType: "bank" },
  { code: "1110", name: "Savings Account", type: "asset", subType: "bank" },
  { code: "1200", name: "Accounts Receivable", type: "asset", subType: "current" },
  { code: "1250", name: "Undeposited Funds", type: "asset", subType: "current" },
  { code: "1260", name: "Income Tax Receivable", type: "asset", subType: "current" },
  { code: "1270", name: "VAT / GST Receivable from Authority", type: "asset", subType: "current" },
  { code: "1290", name: "Allowance for Doubtful Accounts", type: "asset", subType: "current" },
  { code: "1300", name: "Inventory", type: "asset", subType: "current" },
  { code: "1310", name: "Raw Materials", type: "asset", subType: "current" },
  { code: "1320", name: "Finished Goods", type: "asset", subType: "current" },
  { code: "1400", name: "Prepaid Expenses", type: "asset", subType: "current" },
  { code: "1410", name: "Prepaid Insurance", type: "asset", subType: "current" },
  { code: "1500", name: "Input VAT / GST Receivable", type: "asset", subType: "input_vat" },
  { code: "1510", name: "VAT Recoverable from Supplier", type: "asset", subType: "current" },
  { code: "1530", name: "Deferred Input VAT (Cash Scheme)", type: "asset", subType: "current" },
  { code: "1600", name: "Equipment", type: "asset", subType: "fixed" },
  { code: "1610", name: "Furniture & Fixtures", type: "asset", subType: "fixed" },
  { code: "1620", name: "Computer Equipment", type: "asset", subType: "fixed" },
  { code: "1630", name: "Vehicles", type: "asset", subType: "fixed" },
  { code: "1640", name: "Buildings", type: "asset", subType: "fixed" },
  { code: "1650", name: "Land", type: "asset", subType: "fixed" },
  { code: "1700", name: "Accumulated Depreciation - Equipment", type: "asset", subType: "fixed" },
  { code: "1710", name: "Accumulated Depreciation - Furniture", type: "asset", subType: "fixed" },
  { code: "1720", name: "Accumulated Depreciation - Computers", type: "asset", subType: "fixed" },
  { code: "1730", name: "Accumulated Depreciation - Vehicles", type: "asset", subType: "fixed" },
  // Liabilities (2xxx)
  { code: "2000", name: "Accounts Payable", type: "liability", subType: "current" },
  { code: "2100", name: "Accounts Payable - Trade", type: "liability", subType: "current" },
  { code: "2110", name: "Employee Reimbursements Payable", type: "liability", subType: "current" },
  { code: "2150", name: "Goods Received Not Invoiced", type: "liability", subType: "current" },
  { code: "2160", name: "Landed Costs Clearing", type: "liability", subType: "current" },
  { code: "2200", name: "Output VAT / GST Payable", type: "liability", subType: "output_vat" },
  { code: "2220", name: "Income Tax Payable", type: "liability", subType: "current" },
  { code: "2230", name: "Sales Tax Payable", type: "liability", subType: "current" },
  { code: "2235", name: "Payroll Taxes Payable", type: "liability", subType: "current" },
  { code: "2236", name: "Other Statutory Deductions Payable", type: "liability", subType: "current" },
  { code: "2240", name: "VAT / GST Suspense", type: "liability", subType: "current" },
  { code: "2245", name: "Pension & Benefits Payable", type: "liability", subType: "current" },
  { code: "2260", name: "Deferred Output VAT (Cash Scheme)", type: "liability", subType: "current" },
  { code: "2300", name: "Accrued Expenses", type: "liability", subType: "current" },
  { code: "2305", name: "Manufacturing / WIP Clearing", type: "liability", subType: "current" },
  { code: "2310", name: "Wages Payable", type: "liability", subType: "current" },
  { code: "2400", name: "Unearned Revenue", type: "liability", subType: "current" },
  { code: "2410", name: "Customer Deposits", type: "liability", subType: "current" },
  { code: "2500", name: "Short-Term Loans", type: "liability", subType: "current" },
  { code: "2510", name: "Owner / Director Loan Account", type: "liability", subType: "current" },
  { code: "2520", name: "Suspense (to sort later)", type: "liability", subType: "current" },
  { code: "2600", name: "Credit Card Payable", type: "liability", subType: "current" },
  { code: "2700", name: "Long-Term Debt", type: "liability", subType: "non_current" },
  { code: "2800", name: "Mortgage Payable", type: "liability", subType: "non_current" },
  // Equity (3xxx)
  { code: "3000", name: "Owner's Equity", type: "equity", subType: "equity" },
  { code: "3100", name: "Retained Earnings", type: "equity", subType: "retained" },
  { code: "3200", name: "Owner's Drawings", type: "equity", subType: "equity" },
  { code: "3210", name: "Capital Contributions", type: "equity", subType: "equity" },
  { code: "3220", name: "Dividends Paid", type: "equity", subType: "equity" },
  { code: "3300", name: "Common Stock", type: "equity", subType: "equity" },
  { code: "3400", name: "Revaluation Surplus", type: "equity", subType: "equity" },
  // Revenue (4xxx)
  { code: "4000", name: "Sales Revenue", type: "revenue", subType: "operating" },
  { code: "4010", name: "Service Revenue", type: "revenue", subType: "operating" },
  { code: "4020", name: "Consulting Revenue", type: "revenue", subType: "operating" },
  { code: "4100", name: "Interest Income", type: "revenue", subType: "non_operating" },
  { code: "4200", name: "Rental Income", type: "revenue", subType: "non_operating" },
  { code: "4300", name: "Gain on Asset Disposal", type: "revenue", subType: "non_operating" },
  { code: "4400", name: "Bad Debt Recovered", type: "revenue", subType: "non_operating" },
  { code: "4910", name: "Realised Currency Gains", type: "revenue", subType: "non_operating" },
  { code: "4920", name: "Unrealised Currency Gains", type: "revenue", subType: "non_operating" },
  { code: "4900", name: "Other Revenue", type: "revenue", subType: "non_operating" },
  // Expenses (5xxx)
  { code: "5000", name: "Cost of Goods Sold", type: "expense", subType: "cogs" },
  { code: "5010", name: "Inventory Shrinkage", type: "expense", subType: "cogs" },
  { code: "5020", name: "Inventory Write-Down", type: "expense", subType: "cogs" },
  { code: "5050", name: "Purchase Price Variance", type: "expense", subType: "cogs" },
  { code: "5100", name: "Wages & Salaries", type: "expense", subType: "operating" },
  { code: "5110", name: "Employee Benefits", type: "expense", subType: "operating" },
  { code: "5120", name: "Payroll Tax", type: "expense", subType: "operating" },
  { code: "5130", name: "Subcontractor Expense", type: "expense", subType: "operating" },
  { code: "5200", name: "Rent Expense", type: "expense", subType: "operating" },
  { code: "5210", name: "Utilities", type: "expense", subType: "operating" },
  { code: "5220", name: "Internet & Phone", type: "expense", subType: "operating" },
  { code: "5230", name: "Software & Subscriptions", type: "expense", subType: "operating" },
  { code: "5240", name: "Repairs & Maintenance", type: "expense", subType: "operating" },
  { code: "5300", name: "Office Supplies", type: "expense", subType: "operating" },
  { code: "5310", name: "Postage & Shipping", type: "expense", subType: "operating" },
  { code: "5400", name: "Insurance", type: "expense", subType: "operating" },
  { code: "5500", name: "Depreciation Expense", type: "expense", subType: "operating" },
  { code: "5510", name: "Impairment Loss", type: "expense", subType: "operating" },
  { code: "5600", name: "Marketing & Advertising", type: "expense", subType: "operating" },
  { code: "5700", name: "Professional Fees", type: "expense", subType: "operating" },
  { code: "5710", name: "Legal Fees", type: "expense", subType: "operating" },
  { code: "5720", name: "Accounting Fees", type: "expense", subType: "operating" },
  { code: "5800", name: "Travel Expense", type: "expense", subType: "operating" },
  { code: "5810", name: "Meals & Entertainment", type: "expense", subType: "operating" },
  { code: "5820", name: "Motor Vehicle & Fuel", type: "expense", subType: "operating" },
  { code: "5900", name: "Bank Fees & Charges", type: "expense", subType: "operating" },
  { code: "5910", name: "Interest Expense", type: "expense", subType: "non_operating" },
  { code: "5920", name: "Loss on Asset Disposal", type: "expense", subType: "non_operating" },
  { code: "5930", name: "Realised Currency Losses", type: "expense", subType: "non_operating" },
  { code: "5940", name: "Unrealised Currency Losses", type: "expense", subType: "non_operating" },
  { code: "5990", name: "Miscellaneous Expense", type: "expense", subType: "operating" },
  { code: "6500", name: "Bad Debt Expense", type: "expense", subType: "operating" },
  { code: "8200", name: "Income Tax Expense", type: "expense", subType: "non_operating" },
];
