import type { AccountTemplate } from "./types";

/** Italian Piano dei Conti chart of accounts */
export const IT_ACCOUNTS: AccountTemplate[] = [
  // Equity & Long-term Liabilities
  { code: "2101", name: "Share Capital", type: "equity", subType: "equity" },
  { code: "2102", name: "Legal Reserve", type: "equity", subType: "equity" },
  { code: "2103", name: "Extraordinary Reserve", type: "equity", subType: "equity" },
  { code: "2104", name: "Retained Earnings", type: "equity", subType: "retained" },
  { code: "2105", name: "Profit/Loss for the Year", type: "equity", subType: "equity" },
  { code: "2201", name: "Provision for Severance Pay (TFR)", type: "liability", subType: "non_current" },
  { code: "2301", name: "Bank Loans (Long-term)", type: "liability", subType: "non_current" },
  { code: "2302", name: "Mortgage Payable", type: "liability", subType: "non_current" },
  // Fixed Assets
  { code: "1101", name: "Intangible Assets - Software", type: "asset", subType: "fixed" },
  { code: "1102", name: "Intangible Assets - Patents and Licenses", type: "asset", subType: "fixed" },
  { code: "1103", name: "Goodwill (Avviamento)", type: "asset", subType: "fixed" },
  { code: "1201", name: "Land", type: "asset", subType: "fixed" },
  { code: "1202", name: "Buildings", type: "asset", subType: "fixed" },
  { code: "1203", name: "Plant and Machinery", type: "asset", subType: "fixed" },
  { code: "1204", name: "Equipment", type: "asset", subType: "fixed" },
  { code: "1205", name: "Vehicles", type: "asset", subType: "fixed" },
  { code: "1206", name: "Office Furniture and Equipment", type: "asset", subType: "fixed" },
  { code: "1207", name: "Computer Equipment", type: "asset", subType: "fixed" },
  { code: "1210", name: "Accum. Depreciation - Buildings", type: "asset", subType: "fixed" },
  { code: "1211", name: "Accum. Depreciation - Plant & Machinery", type: "asset", subType: "fixed" },
  { code: "1212", name: "Accum. Depreciation - Equipment", type: "asset", subType: "fixed" },
  // Current Assets
  { code: "1301", name: "Raw Materials Inventory", type: "asset", subType: "current" },
  { code: "1302", name: "Finished Goods Inventory", type: "asset", subType: "current" },
  { code: "1303", name: "Goods for Resale", type: "asset", subType: "current" },
  { code: "1401", name: "Trade Receivables", type: "asset", subType: "current" },
  { code: "1402", name: "Notes Receivable", type: "asset", subType: "current" },
  { code: "1404", name: "VAT Receivable (IVA a credito)", type: "asset", subType: "current" },
  { code: "1405", name: "Tax Receivables", type: "asset", subType: "current" },
  { code: "1407", name: "Other Receivables", type: "asset", subType: "current" },
  { code: "1408", name: "Prepaid Expenses", type: "asset", subType: "current" },
  { code: "1501", name: "Bank Accounts", type: "asset", subType: "current" },
  { code: "1502", name: "Petty Cash", type: "asset", subType: "current" },
  // Current Liabilities
  { code: "2401", name: "Trade Payables", type: "liability", subType: "current" },
  { code: "2403", name: "VAT Payable (IVA a debito)", type: "liability", subType: "current" },
  { code: "2404", name: "Withholding Tax Payable", type: "liability", subType: "current" },
  { code: "2405", name: "Social Security Payable (INPS)", type: "liability", subType: "current" },
  { code: "2406", name: "Wages and Salaries Payable", type: "liability", subType: "current" },
  { code: "2407", name: "Income Tax Payable (IRES/IRAP)", type: "liability", subType: "current" },
  { code: "2408", name: "Other Payables", type: "liability", subType: "current" },
  { code: "2409", name: "Short-term Bank Loans", type: "liability", subType: "current" },
  { code: "2410", name: "Deferred Income", type: "liability", subType: "current" },
  // Revenue
  { code: "3101", name: "Sales of Goods", type: "revenue", subType: "operating" },
  { code: "3102", name: "Revenue from Services", type: "revenue", subType: "operating" },
  { code: "3103", name: "Other Operating Revenue", type: "revenue", subType: "operating" },
  { code: "3201", name: "Interest Income", type: "revenue", subType: "non_operating" },
  { code: "3202", name: "Rental Income", type: "revenue", subType: "non_operating" },
  { code: "3203", name: "Gains on Disposal of Fixed Assets", type: "revenue", subType: "non_operating" },
  { code: "3204", name: "Foreign Exchange Gains", type: "revenue", subType: "non_operating" },
  // Expenses
  { code: "4101", name: "Purchases of Goods for Resale", type: "expense", subType: "cogs" },
  { code: "4102", name: "Purchases of Raw Materials", type: "expense", subType: "cogs" },
  { code: "4201", name: "Rent and Leases", type: "expense", subType: "operating" },
  { code: "4202", name: "Utilities (Electricity, Gas, Water)", type: "expense", subType: "operating" },
  { code: "4203", name: "Maintenance and Repairs", type: "expense", subType: "operating" },
  { code: "4204", name: "Insurance", type: "expense", subType: "operating" },
  { code: "4205", name: "Professional Services", type: "expense", subType: "operating" },
  { code: "4206", name: "Transport and Shipping", type: "expense", subType: "operating" },
  { code: "4207", name: "Advertising and Marketing", type: "expense", subType: "operating" },
  { code: "4208", name: "Telecom and Postage", type: "expense", subType: "operating" },
  { code: "4209", name: "Travel and Entertainment", type: "expense", subType: "operating" },
  { code: "4210", name: "Office Supplies", type: "expense", subType: "operating" },
  { code: "4211", name: "Bank Fees and Charges", type: "expense", subType: "operating" },
  { code: "4301", name: "Wages and Salaries", type: "expense", subType: "operating" },
  { code: "4302", name: "Employer Social Security (INPS)", type: "expense", subType: "operating" },
  { code: "4303", name: "Severance Pay Accrual (TFR)", type: "expense", subType: "operating" },
  { code: "4401", name: "Depreciation - Tangible Assets", type: "expense", subType: "operating" },
  { code: "4402", name: "Amortisation - Intangible Assets", type: "expense", subType: "operating" },
  { code: "4501", name: "Interest Expense", type: "expense", subType: "non_operating" },
  { code: "4502", name: "Foreign Exchange Losses", type: "expense", subType: "non_operating" },
  { code: "4601", name: "Income Tax (IRES)", type: "expense", subType: "tax" },
  { code: "4602", name: "Regional Tax (IRAP)", type: "expense", subType: "tax" },
];
