import type { AccountTemplate } from "./types";

/** Portuguese SNC (Sistema de Normalização Contabilistica) chart of accounts */
export const PT_ACCOUNTS: AccountTemplate[] = [
  // Class 1: Cash & Bank
  { code: "11", name: "Cash", type: "asset", subType: "current" },
  { code: "12", name: "Bank Accounts", type: "asset", subType: "current" },
  // Class 2: Receivables & Payables
  { code: "21", name: "Trade Receivables", type: "asset", subType: "current" },
  { code: "211", name: "Domestic Receivables", type: "asset", subType: "current" },
  { code: "22", name: "Trade Payables", type: "liability", subType: "current" },
  { code: "221", name: "Domestic Payables", type: "liability", subType: "current" },
  { code: "231", name: "Employee Advances", type: "asset", subType: "current" },
  { code: "232", name: "Other Debtors", type: "asset", subType: "current" },
  { code: "241", name: "Income Tax Payable (IRC)", type: "liability", subType: "current" },
  { code: "2432", name: "Input VAT (IVA dedutivel)", type: "asset", subType: "current" },
  { code: "2433", name: "Output VAT (IVA liquidado)", type: "liability", subType: "current" },
  { code: "245", name: "Social Security Payable", type: "liability", subType: "current" },
  { code: "262", name: "Salaries Payable", type: "liability", subType: "current" },
  { code: "271", name: "Prepaid Expenses", type: "asset", subType: "current" },
  { code: "272", name: "Deferred Income", type: "liability", subType: "current" },
  { code: "278", name: "Other Receivables / Payables", type: "asset", subType: "current" },
  { code: "279", name: "Allowance for Doubtful Receivables", type: "asset", subType: "current" },
  // Class 3: Inventories
  { code: "31", name: "Purchases of Goods", type: "expense", subType: "cogs" },
  { code: "32", name: "Goods for Resale", type: "asset", subType: "current" },
  { code: "33", name: "Raw Materials", type: "asset", subType: "current" },
  { code: "34", name: "Finished Goods", type: "asset", subType: "current" },
  // Class 4: Fixed Assets
  { code: "43", name: "Tangible Fixed Assets", type: "asset", subType: "fixed" },
  { code: "431", name: "Land", type: "asset", subType: "fixed" },
  { code: "432", name: "Buildings", type: "asset", subType: "fixed" },
  { code: "433", name: "Machinery and Equipment", type: "asset", subType: "fixed" },
  { code: "434", name: "Vehicles", type: "asset", subType: "fixed" },
  { code: "435", name: "Office Equipment", type: "asset", subType: "fixed" },
  { code: "438", name: "Accumulated Depreciation", type: "asset", subType: "fixed" },
  { code: "44", name: "Intangible Assets", type: "asset", subType: "fixed" },
  { code: "441", name: "Software", type: "asset", subType: "fixed" },
  { code: "448", name: "Accumulated Amortisation", type: "asset", subType: "fixed" },
  // Class 5: Equity
  { code: "51", name: "Share Capital", type: "equity", subType: "equity" },
  { code: "55", name: "Legal Reserve", type: "equity", subType: "equity" },
  { code: "56", name: "Retained Earnings", type: "equity", subType: "retained" },
  { code: "59", name: "Other Reserves", type: "equity", subType: "equity" },
  // Class 6: Expenses
  { code: "61", name: "Cost of Goods Sold", type: "expense", subType: "cogs" },
  { code: "62", name: "External Supplies and Services", type: "expense", subType: "operating" },
  { code: "6211", name: "Subcontracting", type: "expense", subType: "operating" },
  { code: "6212", name: "Rent and Leases", type: "expense", subType: "operating" },
  { code: "6214", name: "Insurance", type: "expense", subType: "operating" },
  { code: "6217", name: "Utilities", type: "expense", subType: "operating" },
  { code: "6221", name: "Professional Services", type: "expense", subType: "operating" },
  { code: "6222", name: "Advertising", type: "expense", subType: "operating" },
  { code: "6226", name: "Transport", type: "expense", subType: "operating" },
  { code: "6231", name: "Telecom and Postage", type: "expense", subType: "operating" },
  { code: "6232", name: "Travel and Accommodation", type: "expense", subType: "operating" },
  { code: "6233", name: "Bank Services", type: "expense", subType: "operating" },
  { code: "63", name: "Wages and Salaries", type: "expense", subType: "operating" },
  { code: "635", name: "Employer Social Security", type: "expense", subType: "operating" },
  { code: "64", name: "Depreciation and Amortisation", type: "expense", subType: "operating" },
  { code: "68", name: "Other Operating Expenses", type: "expense", subType: "operating" },
  { code: "691", name: "Interest Expense", type: "expense", subType: "non_operating" },
  { code: "698", name: "Foreign Exchange Losses", type: "expense", subType: "non_operating" },
  { code: "6911", name: "Income Tax (IRC)", type: "expense", subType: "tax" },
  // Class 7: Revenue
  { code: "71", name: "Sales of Goods", type: "revenue", subType: "operating" },
  { code: "72", name: "Revenue from Services", type: "revenue", subType: "operating" },
  { code: "78", name: "Other Operating Income", type: "revenue", subType: "non_operating" },
  { code: "7911", name: "Interest Income", type: "revenue", subType: "non_operating" },
  { code: "785", name: "Gains on Disposal of Fixed Assets", type: "revenue", subType: "non_operating" },
  { code: "788", name: "Foreign Exchange Gains", type: "revenue", subType: "non_operating" },
];
