import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "google-text": "var(--google-text)",
        "google-text-secondary": "var(--google-text-secondary)",
        "google-border": "var(--google-border)",
        "google-bg": "var(--google-bg)",
        "google-card": "var(--google-card)",
        "google-primary": "var(--google-primary)",
        "google-hover": "var(--google-hover)",
        "google-selected": "var(--google-selected)",
        "on-primary": "#ffffff",
        "secondary-fixed": "#89f5e7",
        "on-secondary-fixed": "#00201d",
        "surface-dim": "#d9dadb",
        "outline": "#757682",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "secondary": "#006a61",
        "primary-fixed": "#dce1ff",
        "surface-container-low": "#f3f4f5",
        "on-secondary-container": "#006f66",
        "tertiary-fixed-dim": "#d2bbff",
        "error-container": "#ffdad6",
        "on-background": "#191c1d",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#264191",
        "inverse-surface": "#2e3132",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-container": "#bc9bff",
        "on-surface": "#191c1d",
        "tertiary": "#37007e",
        "primary": "#00236f",
        "inverse-primary": "#b6c4ff",
        "on-surface-variant": "#444651",
        "tertiary-fixed": "#eaddff",
        "surface-tint": "#4059aa",
        "outline-variant": "#c5c5d3",
        "on-tertiary-fixed": "#25005a",
        "on-primary-fixed": "#00164e",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-container": "#90a8ff",
        "primary-container": "#1e3a8a",
        "surface-bright": "#f8f9fa",
        "on-error": "#ffffff",
        "background": "#f8f9fa",
        "surface-container": "#edeeef",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#005049",
        "surface-variant": "#e1e3e4",
        "secondary-fixed-dim": "#6bd8cb",
        "surface": "#f8f9fa",
        "primary-fixed-dim": "#b6c4ff",
        "on-tertiary-fixed-variant": "#5a00c6",
        "tertiary-container": "#5200b5",
        "secondary-container": "#86f2e4",
      },
      fontFamily: {
        mono:     ['"SF Mono"', '"SFMono-Regular"', "ui-monospace", "Menlo", "Monaco", "Consolas", '"Liberation Mono"', '"Courier New"', "monospace"],
        sans:     ['"SF Mono"', '"SFMono-Regular"', "ui-monospace", "Menlo", "Monaco", "Consolas", '"Liberation Mono"', '"Courier New"', "monospace"],
        inter:    ['"SF Mono"', '"SFMono-Regular"', "ui-monospace", "Menlo", "Monaco", "Consolas", '"Liberation Mono"', '"Courier New"', "monospace"],
        body:     ['"SF Mono"', '"SFMono-Regular"', "ui-monospace", "Menlo", "Monaco", "Consolas", '"Liberation Mono"', '"Courier New"', "monospace"],
        display:  ['"SF Mono"', '"SFMono-Regular"', "ui-monospace", "Menlo", "Monaco", "Consolas", '"Liberation Mono"', '"Courier New"', "monospace"],
        headline: ['"SF Mono"', '"SFMono-Regular"', "ui-monospace", "Menlo", "Monaco", "Consolas", '"Liberation Mono"', '"Courier New"', "monospace"],
        label:    ['"SF Mono"', '"SFMono-Regular"', "ui-monospace", "Menlo", "Monaco", "Consolas", '"Liberation Mono"', '"Courier New"', "monospace"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
export default config;
